/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa_23130628_proyecto_02;

import Utilerias.JTable.ColorCeldas;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fer Landa Santi
 */
public class PA_23130628_Frame_02 extends javax.swing.JFrame {

    /**
     * Creates new form PA_23130628_Frame_01
     */
    
    private DefaultTableModel modelo;
    public PA_23130628_Frame_02() {
        initComponents();
        // ponemos el DefaultTableModel para que nos ponga las funciones de las tablas de java y trabajar mas facil
        modelo = (DefaultTableModel) jTableHostales.getModel();
        
        jTableHostales.setShowGrid(true);
        
        jTableTotales.setShowVerticalLines(true);        
        jTableTotales.setValueAt("TOTALES", 0, 0);
    }
    // Este metodo es para borrar los datos de la tabla implementando un ciclo y que nos ponga los valores en nulos osea en blanco
    public void borrar(){

        blanco();
for(int r = 0; r < modelo.getRowCount(); r++)
            for(int c=0; c < modelo.getColumnCount(); c++)
                modelo.setValueAt(null, r, c);

        for(int r = 0; r < jTableTotales.getRowCount(); r++)
            for(int c=1; c < jTableTotales.getColumnCount(); c++)
                jTableTotales.setValueAt(null, r, c);
        


    }
    // Este metodo hace que las celdas esten de color blanco utilizando la libreria para colorear renglones o celdas del jtable
    // igual utilizamos un ciclo para generar los renglones del jtable y luego los ponemos en blanco y ponemos repaint para reiniciar la tabla
    public void blanco(){
                ColorCeldas color = new ColorCeldas(jTableHostales);
        for(int r = 0; r < modelo.getRowCount(); r++)
            for(int c=0; c < modelo.getColumnCount(); c++)
                color.addCelda(r, c, Color.white);
                color.repaint();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHostales = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinHostal = new javax.swing.JSpinner();
        jButCalcular = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButOrdenar = new javax.swing.JButton();
        jButOrdenarVenta = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jButEjemplo1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTotales = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextHostal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButSeñalar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 900));

        jTableHostales.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTableHostales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hostal", "Moyo", "Cántara", "Azumbre", "Cuartillo", "Moyo", "Cántara", "Azumbre", "Cuartillo", "Moyo", "Cántara", "Azumbre", "Cuartillo"
            }
        ));
        jScrollPane1.setViewportView(jTableHostales);
        if (jTableHostales.getColumnModel().getColumnCount() > 0) {
            jTableHostales.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableHostales.getColumnModel().getColumn(4).setHeaderValue("Cuartillo");
            jTableHostales.getColumnModel().getColumn(5).setHeaderValue("Moyo");
            jTableHostales.getColumnModel().getColumn(6).setHeaderValue("Cántara");
            jTableHostales.getColumnModel().getColumn(7).setHeaderValue("Azumbre");
            jTableHostales.getColumnModel().getColumn(8).setHeaderValue("Cuartillo");
            jTableHostales.getColumnModel().getColumn(9).setHeaderValue("Moyo");
            jTableHostales.getColumnModel().getColumn(10).setHeaderValue("Cántara");
            jTableHostales.getColumnModel().getColumn(11).setHeaderValue("Azumbre");
            jTableHostales.getColumnModel().getColumn(12).setHeaderValue("Cuartillo");
        }

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inventario Inicial");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 0, 51));
        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventas");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inventario Final");
        jLabel4.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("No. Hostales");

        jSpinHostal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinHostal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinHostalStateChanged(evt);
            }
        });

        jButCalcular.setBackground(new java.awt.Color(204, 255, 204));
        jButCalcular.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorios.setBackground(new java.awt.Color(204, 204, 204));
        jButAleatorios.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButOrdenar.setBackground(new java.awt.Color(255, 255, 204));
        jButOrdenar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButOrdenar.setText("Orden Alfabetico");
        jButOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenarActionPerformed(evt);
            }
        });

        jButOrdenarVenta.setBackground(new java.awt.Color(204, 204, 255));
        jButOrdenarVenta.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButOrdenarVenta.setText("Ordenar por venta");
        jButOrdenarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenarVentaActionPerformed(evt);
            }
        });

        jButBorrar.setBackground(new java.awt.Color(255, 204, 204));
        jButBorrar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jButEjemplo1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jButEjemplo1.setText("Ejemplo");
        jButEjemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemplo1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_23130628_proyecto_02/Ejemplo.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        jTableTotales.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jTableTotales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Moyo", "Cántara", "Azumbre", "Cuartillos", "Moyo", "Cántara", "Azumbre", "Cuartillos", "Moyo", "Cántara", "Azumbre", "Cuartillos"
            }
        ));
        jTableTotales.setRowHeight(30);
        jScrollPane2.setViewportView(jTableTotales);
        if (jTableTotales.getColumnModel().getColumnCount() > 0) {
            jTableTotales.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_23130628_proyecto_02/Asignacion.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel9.setText("¿Cuál hostal deseas buscar?");

        jButSeñalar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jButSeñalar.setText("Señalar");
        jButSeñalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSeñalarActionPerformed(evt);
            }
        });

        jLabel10.setBackground(java.awt.Color.green);
        jLabel10.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Hostal seleccionado por el usuario");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ARREGLO ENCAPSULADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(836, 836, 836)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jTextHostal, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButSeñalar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinHostal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(jButAleatorios)
                        .addGap(18, 18, 18)
                        .addComponent(jButOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButOrdenarVenta)
                        .addGap(43, 43, 43)
                        .addComponent(jButBorrar)
                        .addGap(32, 32, 32)
                        .addComponent(jButEjemplo1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinHostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButCalcular)
                        .addComponent(jButAleatorios)
                        .addComponent(jButOrdenar)
                        .addComponent(jButOrdenarVenta)
                        .addComponent(jButBorrar)
                        .addComponent(jButEjemplo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButSeñalar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHostal))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(684, 684, 684))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinHostalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinHostalStateChanged
        // TODO add your handling code here:
        // aqui hago que la tabla genere renglones segun el valor del spiner
        modelo.setRowCount((int)jSpinHostal.getValue());
        
        
    }//GEN-LAST:event_jSpinHostalStateChanged

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
        
        //agregamos un random para generar datos aleatorios
        Random azar = new Random();
        // cada ves que pongamos datos aleatorios borrara los anteriores con el metodo borrar
       borrar();
       //Utilizamos los objetos de las clases y los metodos de ellas
       Industria alehotels = new Industria(0);
       alehotels.aleatorios(jTableHostales);

        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        
        //Utilizamos los objetos de las clases y los metodos de ellas
        Industria hoteles = new Industria(0);
        hoteles.mostrar(jTableHostales, jTableTotales);  
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenarActionPerformed
        // TODO add your handling code here:
        //al momento de ordenar pongo que me coloree de color blanco por si algun renglon se pinto que lo resetee
                blanco();
                // utilizo el objeto Industria para que me guarde datos en un arreglo
        Industria hotels = new Industria(modelo.getRowCount());
        // genero un ciclo que me pondra los valores de las columnas en el jtable
        for(int r = 0; r < modelo.getRowCount(); r++){
            Vino iniciales = new Vino();
            iniciales.setMoyo(Integer.parseInt(modelo.getValueAt(r, 1) + ""));
            iniciales.setCantara(Integer.parseInt(modelo.getValueAt(r, 2) + ""));
            iniciales.setAzumbre(Integer.parseInt(modelo.getValueAt(r, 3) + ""));
            iniciales.setCuartillo(Integer.parseInt(modelo.getValueAt(r, 4) + ""));
            
            Vino finales = new Vino();
            finales.setMoyo(Integer.parseInt(modelo.getValueAt(r, 5) + ""));
            finales.setCantara(Integer.parseInt(modelo.getValueAt(r, 6) + ""));
            finales.setAzumbre(Integer.parseInt(modelo.getValueAt(r, 7) + ""));
            finales.setCuartillo(Integer.parseInt(modelo.getValueAt(r, 8) + ""));
            
            Huesped hues = new Huesped(modelo.getValueAt(r, 0) + "", iniciales, finales);
            hotels.setHuesped(hues, r);
        }
        //Utilizo el ordenamiento echo en una clase
       hotels.alfabetico();
        //Este ciclo ingresa los valores calculados y ordenados al table
        for(int r = 0; r < modelo.getRowCount(); r++)
        {
            modelo.setValueAt(hotels.getHuesped(r).getHoteles(), r, 0);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getMoyo(), r, 1);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getCantara(), r, 2);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getAzumbre(), r, 3);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getCuartillo(), r, 4);
            
            
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getMoyo(), r, 5);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getCantara(), r, 6);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getAzumbre(), r, 7);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getCuartillo(), r, 8);
            
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getMoyo(), r, 9);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getCantara(), r, 10);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getAzumbre(), r, 11);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getCuartillo(), r, 12);
        }
     
        
      
    }//GEN-LAST:event_jButOrdenarActionPerformed

    private void jButOrdenarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenarVentaActionPerformed
        // TODO add your handling code here:
        
        //al momento de ordenar pongo que me coloree de color blanco por si algun renglon se pinto que lo resetee
        blanco();
        // Utilizo un objeto para que me guarde los valores en un arreglo
    Industria hotels = new Industria(modelo.getRowCount());
    // genero un ciclo que me pondra los valores de las columnas en el jtable
        for(int r = 0; r < modelo.getRowCount(); r++){
            Vino iniciales = new Vino();
            iniciales.setMoyo(Integer.parseInt(modelo.getValueAt(r, 1) + ""));
            iniciales.setCantara(Integer.parseInt(modelo.getValueAt(r, 2) + ""));
            iniciales.setAzumbre(Integer.parseInt(modelo.getValueAt(r, 3) + ""));
            iniciales.setCuartillo(Integer.parseInt(modelo.getValueAt(r, 4) + ""));
            
            Vino finales = new Vino();
            finales.setMoyo(Integer.parseInt(modelo.getValueAt(r, 5) + ""));
            finales.setCantara(Integer.parseInt(modelo.getValueAt(r, 6) + ""));
            finales.setAzumbre(Integer.parseInt(modelo.getValueAt(r, 7) + ""));
            finales.setCuartillo(Integer.parseInt(modelo.getValueAt(r, 8) + ""));
            
            Huesped hues = new Huesped(modelo.getValueAt(r, 0) + "", iniciales, finales);
            hotels.setHuesped(hues, r);
        }
        // Utilizo un ordenamiento echo en una clase
       hotels.ordenar();
        //Este ciclo ingresa los valores calculados y ordenados al table
        for(int r = 0; r < modelo.getRowCount(); r++)
        {
            modelo.setValueAt(hotels.getHuesped(r).getHoteles(), r, 0);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getMoyo(), r, 1);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getCantara(), r, 2);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getAzumbre(), r, 3);
            modelo.setValueAt(hotels.getHuesped(r).getIniciales().getCuartillo(), r, 4);
            
            
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getMoyo(), r, 5);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getCantara(), r, 6);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getAzumbre(), r, 7);
            modelo.setValueAt(hotels.getHuesped(r).getFinales().getCuartillo(), r, 8);
            
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getMoyo(), r, 9);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getCantara(), r, 10);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getAzumbre(), r, 11);
            modelo.setValueAt(hotels.getHuesped(r).ventaTotal().getCuartillo(), r, 12);
        }
    }//GEN-LAST:event_jButOrdenarVentaActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        // Utilizo el metedo de borrar
        borrar();
    }//GEN-LAST:event_jButBorrarActionPerformed

    private void jButEjemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemplo1ActionPerformed
        // TODO add your handling code here:
        
        // Para el ejemplo ingreso el numero de renglones al spiner para que me los refleje la tabla
        jSpinHostal.setValue(4);
        //modelo.setRowCount(4);
        // cada ves que se presiona el boton, se borraran los datos anteriores
        borrar();
        // utilizo una clase en donde hay un metodo que contiene el ejemplo
       Industria ejem = new Industria(0);
       ejem.ejemplo(jTableHostales);        

        
    }//GEN-LAST:event_jButEjemplo1ActionPerformed

    private void jButSeñalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSeñalarActionPerformed
        // TODO add your handling code here:
        
        // Hago que el texto ingresado por el usuario sea tipo string y en minusculas
        String textoIngresado = jTextHostal.getText().toLowerCase();       
        // Agrego una variable de tipo boolean para luego hacer que funcione una condicion
        boolean encontrado = false;
        //Utilizo la libreria de los colores y hago un objeto nuevo
      ColorCeldas color = new ColorCeldas(jTableHostales);
       // El ciclo me genera los renglones y columnas del jtable
      for(int c=0; c < jTableHostales.getColumnCount(); c++){
           for(int r = 0; r < jTableHostales.getRowCount(); r++){  
               // convierto a string el valor de la columna 0 del table y lo hago minusculas tambien
            String valorCelda = String.valueOf(jTableHostales.getValueAt(r, 0)).toLowerCase();
            // se compara el valor ingresado por el usuario y el tomado del table
          if(textoIngresado.equals(valorCelda)){
              // si esto es cierto se colorea el renglon en donde se encuentra
          color.addCelda(r, c, Color.green);      
          encontrado = true; // Se encontró el hostal
          
          }
           }
           }
              
      color.repaint();
      // si no es cierto sale un mensaje
      if (!encontrado) {
    JOptionPane.showMessageDialog(rootPane, "Hostal no encontrado");
      }
    }//GEN-LAST:event_jButSeñalarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_23130628_Frame_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_23130628_Frame_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo1;
    private javax.swing.JButton jButOrdenar;
    private javax.swing.JButton jButOrdenarVenta;
    private javax.swing.JButton jButSeñalar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinHostal;
    private javax.swing.JTable jTableHostales;
    private javax.swing.JTable jTableTotales;
    private javax.swing.JTextField jTextHostal;
    // End of variables declaration//GEN-END:variables
}
